[package]
name = "zappy_42"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"

[[bin]]
name = "server"
path = "src/server/main.rs"


[[bin]]
name = "client"
path = "src/client/main.rs"
